# This file is a template, and might need editing before it works on your project.
# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
image: ubuntu:16.04

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - apt update -y
  - apt install openjdk-8-jdk -y
  - apt install npm -y
  - apt install git -y

build:
  stage: build
  script: 
    - ./gradlew --build-cache distTar
    - ./gradlew installDist
    - ls -la
    - npm version patch -m "Updated version"
    - git push
    - cp ./package.json ./build/install/phoenix-adapter
    - cd build/install/phoenix-adapter
    - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
  artifacts:
    paths:
        - build/distributions/phoenix-adapter.tar
    expire_in: 1 week
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
      

# publish:
#   stage: publish
#   script: ./gradlew installDist
#   cache:
#     key: "$CI_COMMIT_REF_NAME"
#     policy: pull
#     paths:
#       - build
#       - .gradle


