
language: node_js

node_js:
  - "10.7.0"


install:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - sudo apt update -y
  - sudo apt install openjdk-8-jdk -y
  - sudo apt install npm -y

script:
  - ./gradlew --build-cache distTar
  - ./gradlew installDist
  - ls -la
  - cp ./package.json ./build/install/phoenix-adapter
  - cd build/install/phoenix-adapter
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
  - npm publish || true


