
#variables:
#  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

install:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - apt update -y
  - apt install gradle
  - apt install openjdk-8-jdk -y
  - apt install npm -y

script:
  - ./gradlew --build-cache distTar
  - ./gradlew installDist
  - ls -la
  - cp ./package.json ./build/install/phoenix-adapter
  - cd build/install/phoenix-adapter
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
  - npm publish
#artifacts:
#  paths:
#      - build/distributions/phoenix-adapter.tar
#  expire_in: 1 week
#cache:
#  key: "$CI_COMMIT_REF_NAME"
#  policy: push
#  paths:
#    - build
#    - .gradle


